language: bash
services: docker

env:
  - VERSION=2.4
  - VERSION=2.4 VARIANT=alpine

install:
  - git clone https://github.com/docker-library/official-images.git ~/official-images

before_script:
  - env | sort
  - wget -qO- 'https://github.com/tianon/pgp-happy-eyeballs/raw/master/hack-my-builds.sh' | bash
  - cd "$VERSION/$VARIANT"
  - image="httpd:${VERSION}${VARIANT:+-$VARIANT}"

script:
  - |
    (
      set -Eeuo pipefail
      set -x
      docker build -t artsdatabanken:httpd .
      ~/official-images/test/run.sh artsdatabanken:httpd
    )

after_script:
  - docker images
  
after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push artsdatabanken:httpd;
    fi

# vim:set et ts=2 sw=2:
