# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

steps:
- script: |
    docker build -f $(Build.SourcesDirectory)/2.4/alpine/Dockerfile -t $(dockerId)/$(imageName) .
    docker login -u $(dockerUser) -p $pwd
    docker push $(dockerId)/$(imageName)
  env:
    pwd: $dockerPass